from collections.abc import Sequence
from typing import Literal, Protocol, overload

from . import ExifTags as ExifTags
from . import Image as Image
from . import ImagePalette as ImagePalette

def _border(border: int | tuple[int, ...]) -> tuple[int, int, int, int]: ...
def _color(color: str | int | tuple[int, ...], mode: str) -> int | tuple[int, ...]: ...
def _lut(image: Image.Image, lut: list[int]) -> Image.Image: ...
def autocontrast(
    image: Image.Image,
    cutoff: float | tuple[float, float] = 0,
    ignore: int | Sequence[int] | None = None,
    mask: Image.Image | None = None,
    preserve_tone: bool = False,
) -> Image.Image: ...
def colorize(
    image: Image.Image,
    black: str | tuple[int, ...],
    white: str | tuple[int, ...],
    mid: str | int | tuple[int, ...] | None = None,
    blackpoint: int = 0,
    whitepoint: int = 255,
    midpoint: int = 127,
) -> Image.Image: ...
def contain(image: Image.Image, size: tuple[int, int], method: int = ...) -> Image.Image: ...
def cover(image: Image.Image, size: tuple[int, int], method: int = ...) -> Image.Image: ...
def pad(
    image: Image.Image,
    size: tuple[int, int],
    method: int = ...,
    color: str | int | tuple[int, ...] | None = None,
    centering: tuple[float, float] = (0.5, 0.5),
) -> Image.Image: ...
def crop(image: Image.Image, border: int = 0) -> Image.Image: ...
def scale(image: Image.Image, factor: float, resample: int = ...) -> Image.Image: ...

class SupportsGetMesh(Protocol):
    def getmesh(self, image: Image.Image) -> list[tuple[tuple[int, int, int, int], tuple[int, int, int, int, int, int, int, int]]]: ...

def deform(image: Image.Image, deformer: SupportsGetMesh, resample: int = ...) -> Image.Image: ...
def equalize(image: Image.Image, mask: Image.Image | None = None) -> Image.Image: ...
def expand(image: Image.Image, border: int | tuple[int, ...] = 0, fill: str | int | tuple[int, ...] = 0) -> Image.Image: ...
def fit(
    image: Image.Image, size: tuple[int, int], method: int = ..., bleed: float = 0.0, centering: tuple[float, float] = (0.5, 0.5)
) -> Image.Image: ...
def flip(image: Image.Image) -> Image.Image: ...
def grayscale(image: Image.Image) -> Image.Image: ...
def invert(image: Image.Image) -> Image.Image: ...
def mirror(image: Image.Image) -> Image.Image: ...
def posterize(image: Image.Image, bits: int) -> Image.Image: ...
def solarize(image: Image.Image, threshold: int = 128) -> Image.Image: ...
@overload
def exif_transpose(image: Image.Image, *, in_place: Literal[True]) -> None: ...
@overload
def exif_transpose(image: Image.Image, *, in_place: Literal[False] = False) -> Image.Image: ...
