import abc
import mmap
from collections.abc import Callable as Callable
from collections.abc import Iterator, MutableMapping, Sequence
from enum import IntEnum
from types import ModuleType
from typing import IO, Any, Literal, Protocol, TypeAlias

from _typeshed import Incomplete
from IPython.lib.pretty import PrettyPrinter as PrettyPrinter

from . import ExifTags as ExifTags
from . import ImageFile as ImageFile
from . import ImageFilter as ImageFilter
from . import ImageMode as ImageMode
from . import ImagePalette as ImagePalette
from . import ImageQt as ImageQt
from . import TiffImagePlugin as TiffImagePlugin
from . import TiffTags as TiffTags
from . import UnidentifiedImageError as UnidentifiedImageError
from . import __version__ as __version__
from . import _imaging as core
from . import _plugins as _plugins
from ._binary import i32le as i32le
from ._binary import o32be as o32be
from ._binary import o32le as o32le
from ._deprecate import deprecate as deprecate
from ._typing import CapsuleType as CapsuleType
from ._typing import NumpyArray as NumpyArray
from ._typing import StrOrBytesPath as StrOrBytesPath
from ._util import DeferredError as DeferredError
from ._util import is_path as is_path

ElementTree: ModuleType | None
TYPE_CHECKING: bool
logger: Incomplete

class DecompressionBombWarning(RuntimeWarning): ...
class DecompressionBombError(Exception): ...

WARN_POSSIBLE_FORMATS: bool
MAX_IMAGE_PIXELS: int | None
msg: Incomplete

class Transpose(IntEnum):
    FLIP_LEFT_RIGHT = 0
    FLIP_TOP_BOTTOM = 1
    ROTATE_90 = 2
    ROTATE_180 = 3
    ROTATE_270 = 4
    TRANSPOSE = 5
    TRANSVERSE = 6

class Transform(IntEnum):
    AFFINE = 0
    EXTENT = 1
    PERSPECTIVE = 2
    QUAD = 3
    MESH = 4

class Resampling(IntEnum):
    NEAREST = 0
    BOX = 4
    BILINEAR = 2
    HAMMING = 5
    BICUBIC = 3
    LANCZOS = 1

_filters_support: Incomplete

class Dither(IntEnum):
    NONE = 0
    ORDERED = 1
    RASTERIZE = 2
    FLOYDSTEINBERG = 3

class Palette(IntEnum):
    WEB = 0
    ADAPTIVE = 1

class Quantize(IntEnum):
    MEDIANCUT = 0
    MAXCOVERAGE = 1
    FASTOCTREE = 2
    LIBIMAGEQUANT = 3

module: Incomplete
DEFAULT_STRATEGY: Incomplete
FILTERED: Incomplete
HUFFMAN_ONLY: Incomplete
RLE: Incomplete
FIXED: Incomplete
ID: list[str]
OPEN: dict[str, tuple[Callable[[IO[bytes], str | bytes], ImageFile.ImageFile], Callable[[bytes], bool | str] | None]]
MIME: dict[str, str]
SAVE: dict[str, Callable[[Image, IO[bytes], str | bytes], None]]
SAVE_ALL: dict[str, Callable[[Image, IO[bytes], str | bytes], None]]
EXTENSION: dict[str, str]
DECODERS: dict[str, type[ImageFile.PyDecoder]]
ENCODERS: dict[str, type[ImageFile.PyEncoder]]
_ENDIAN: Incomplete

def _conv_type_shape(im: Image) -> tuple[tuple[int, ...], str]: ...

MODES: Incomplete
_MAPMODES: Incomplete

def getmodebase(mode: str) -> str: ...
def getmodetype(mode: str) -> str: ...
def getmodebandnames(mode: str) -> tuple[str, ...]: ...
def getmodebands(mode: str) -> int: ...

_initialized: int

def preinit() -> None: ...
def init() -> bool: ...
def _getdecoder(mode: str, decoder_name: str, args: Any, extra: tuple[Any, ...] = ()) -> core.ImagingDecoder | ImageFile.PyDecoder: ...
def _getencoder(mode: str, encoder_name: str, args: Any, extra: tuple[Any, ...] = ()) -> core.ImagingEncoder | ImageFile.PyEncoder: ...

class ImagePointTransform:
    scale: Incomplete
    offset: Incomplete
    def __init__(self, scale: float, offset: float) -> None: ...
    def __neg__(self) -> ImagePointTransform: ...
    def __add__(self, other: ImagePointTransform | float) -> ImagePointTransform: ...
    __radd__ = __add__
    def __sub__(self, other: ImagePointTransform | float) -> ImagePointTransform: ...
    def __rsub__(self, other: ImagePointTransform | float) -> ImagePointTransform: ...
    def __mul__(self, other: ImagePointTransform | float) -> ImagePointTransform: ...
    __rmul__ = __mul__
    def __truediv__(self, other: ImagePointTransform | float) -> ImagePointTransform: ...

def _getscaleoffset(expr: Callable[[ImagePointTransform], ImagePointTransform | float]) -> tuple[float, float]: ...

class SupportsGetData(Protocol):
    def getdata(self) -> tuple[Transform, Sequence[int]]: ...

class Image:
    format: str | None
    format_description: str | None
    _close_exclusive_fp_after_loading: bool
    _im: core.ImagingCore | DeferredError | None
    _mode: str
    _size: Incomplete
    palette: ImagePalette.ImagePalette | None
    info: dict[str | tuple[int, int], Any]
    _exif: Exif | None
    def __init__(self) -> None: ...
    @property
    def im(self) -> core.ImagingCore: ...
    @im.setter
    def im(self, im: core.ImagingCore) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def size(self) -> tuple[int, int]: ...
    @property
    def mode(self) -> str: ...
    @property
    def readonly(self) -> int: ...
    _readonly: Incomplete
    @readonly.setter
    def readonly(self, readonly: int) -> None: ...
    def _new(self, im: core.ImagingCore) -> Image: ...
    def __enter__(self): ...
    fp: Incomplete
    def __exit__(self, *args) -> None: ...
    map: mmap.mmap | None
    def close(self) -> None: ...
    def _copy(self) -> None: ...
    def _ensure_mutable(self) -> None: ...
    def _dump(self, file: str | None = None, format: str | None = None, **options: Any) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def _repr_pretty_(self, p: PrettyPrinter, cycle: bool) -> None: ...
    def _repr_image(self, image_format: str, **kwargs: Any) -> bytes | None: ...
    def _repr_png_(self) -> bytes | None: ...
    def _repr_jpeg_(self) -> bytes | None: ...
    @property
    def __array_interface__(self) -> dict[str, str | bytes | int | tuple[int, ...]]: ...
    def __arrow_c_schema__(self) -> object: ...
    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, object]: ...
    def __getstate__(self) -> list[Any]: ...
    def __setstate__(self, state: list[Any]) -> None: ...
    def tobytes(self, encoder_name: str = "raw", *args: Any) -> bytes: ...
    def tobitmap(self, name: str = "image") -> bytes: ...
    def frombytes(self, data: bytes | bytearray | SupportsArrayInterface, decoder_name: str = "raw", *args: Any) -> None: ...
    def load(self) -> core.PixelAccess | None: ...
    def verify(self) -> None: ...
    def convert(
        self,
        mode: str | None = None,
        matrix: tuple[float, ...] | None = None,
        dither: Dither | None = None,
        palette: Palette = ...,
        colors: int = 256,
    ) -> Image: ...
    def quantize(
        self, colors: int = 256, method: int | None = None, kmeans: int = 0, palette: Image | None = None, dither: Dither = ...
    ) -> Image: ...
    def copy(self) -> Image: ...
    __copy__ = copy
    def crop(self, box: tuple[float, float, float, float] | None = None) -> Image: ...
    def _crop(self, im: core.ImagingCore, box: tuple[float, float, float, float]) -> core.ImagingCore: ...
    def draft(self, mode: str | None, size: tuple[int, int] | None) -> tuple[str, tuple[int, int, float, float]] | None: ...
    def filter(self, filter: ImageFilter.Filter | type[ImageFilter.Filter]) -> Image: ...
    def getbands(self) -> tuple[str, ...]: ...
    def getbbox(self, *, alpha_only: bool = True) -> tuple[int, int, int, int] | None: ...
    def getcolors(self, maxcolors: int = 256) -> list[tuple[int, tuple[int, ...]]] | list[tuple[int, float]] | None: ...
    def getdata(self, band: int | None = None) -> core.ImagingCore: ...
    def getextrema(self) -> tuple[float, float] | tuple[tuple[int, int], ...]: ...
    def getxmp(self) -> dict[str, Any]: ...
    def getexif(self) -> Exif: ...
    def _reload_exif(self) -> None: ...
    def get_child_images(self) -> list[ImageFile.ImageFile]: ...
    def getim(self) -> CapsuleType: ...
    def getpalette(self, rawmode: str | None = "RGB") -> list[int] | None: ...
    @property
    def has_transparency_data(self) -> bool: ...
    def apply_transparency(self) -> None: ...
    def getpixel(self, xy: tuple[int, int] | list[int]) -> float | tuple[int, ...] | None: ...
    def getprojection(self) -> tuple[list[int], list[int]]: ...
    def histogram(self, mask: Image | None = None, extrema: tuple[float, float] | None = None) -> list[int]: ...
    def entropy(self, mask: Image | None = None, extrema: tuple[float, float] | None = None) -> float: ...
    def paste(
        self,
        im: Image | str | float | tuple[float, ...],
        box: Image | tuple[int, int, int, int] | tuple[int, int] | None = None,
        mask: Image | None = None,
    ) -> None: ...
    def alpha_composite(self, im: Image, dest: Sequence[int] = (0, 0), source: Sequence[int] = (0, 0)) -> None: ...
    def point(
        self,
        lut: Sequence[float]
        | NumpyArray
        | Callable[[int], float]
        | Callable[[ImagePointTransform], ImagePointTransform | float]
        | ImagePointHandler,
        mode: str | None = None,
    ) -> Image: ...
    def putalpha(self, alpha: Image | int) -> None: ...
    def putdata(
        self, data: Sequence[float] | Sequence[Sequence[int]] | core.ImagingCore | NumpyArray, scale: float = 1.0, offset: float = 0.0
    ) -> None: ...
    def putpalette(self, data: ImagePalette.ImagePalette | bytes | Sequence[int], rawmode: str = "RGB") -> None: ...
    def putpixel(self, xy: tuple[int, int], value: float | tuple[int, ...] | list[int]) -> None: ...
    def remap_palette(self, dest_map: list[int], source_palette: bytes | bytearray | None = None) -> Image: ...
    def _get_safe_box(
        self, size: tuple[int, int], resample: Resampling, box: tuple[float, float, float, float]
    ) -> tuple[int, int, int, int]: ...
    def resize(
        self,
        size: tuple[int, int] | list[int] | NumpyArray,
        resample: int | None = None,
        box: tuple[float, float, float, float] | None = None,
        reducing_gap: float | None = None,
    ) -> Image: ...
    def reduce(self, factor: int | tuple[int, int], box: tuple[int, int, int, int] | None = None) -> Image: ...
    def rotate(
        self,
        angle: float,
        resample: Resampling = ...,
        expand: int | bool = False,
        center: tuple[float, float] | None = None,
        translate: tuple[int, int] | None = None,
        fillcolor: float | tuple[float, ...] | str | None = None,
    ) -> Image: ...
    _default_encoderinfo: Incomplete
    encoderconfig: tuple[Any, ...]
    encoderinfo: Incomplete
    def save(self, fp: StrOrBytesPath | IO[bytes], format: str | None = None, **params: Any) -> None: ...
    def _attach_default_encoderinfo(self, im: Image) -> dict[str, Any]: ...
    def seek(self, frame: int) -> None: ...
    def show(self, title: str | None = None) -> None: ...
    def split(self) -> tuple[Image, ...]: ...
    def getchannel(self, channel: int | str) -> Image: ...
    def tell(self) -> int: ...
    def thumbnail(self, size: tuple[float, float], resample: Resampling = ..., reducing_gap: float | None = 2.0) -> None: ...
    def transform(
        self,
        size: tuple[int, int],
        method: Transform | ImageTransformHandler | SupportsGetData,
        data: Sequence[Any] | None = None,
        resample: int = ...,
        fill: int = 1,
        fillcolor: float | tuple[float, ...] | str | None = None,
    ) -> Image: ...
    def __transformer(
        self, box: tuple[int, int, int, int], image: Image, method: Transform, data: Sequence[float], resample: int = ..., fill: bool = True
    ) -> None: ...
    def transpose(self, method: Transpose) -> Image: ...
    def effect_spread(self, distance: int) -> Image: ...
    def toqimage(self) -> ImageQt.ImageQt: ...
    def toqpixmap(self) -> ImageQt.QPixmap: ...

class ImagePointHandler(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def point(self, im: Image) -> Image: ...

class ImageTransformHandler(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def transform(self, size: tuple[int, int], image: Image, **options: Any) -> Image: ...

def _check_size(size: Any) -> None: ...
def new(mode: str, size: tuple[int, int] | list[int], color: float | tuple[float, ...] | str | None = 0) -> Image: ...
def frombytes(
    mode: str, size: tuple[int, int], data: bytes | bytearray | SupportsArrayInterface, decoder_name: str = "raw", *args: Any
) -> Image: ...
def frombuffer(mode: str, size: tuple[int, int], data: bytes | SupportsArrayInterface, decoder_name: str = "raw", *args: Any) -> Image: ...

class SupportsArrayInterface(Protocol):
    @property
    def __array_interface__(self) -> dict[str, Any]: ...

class SupportsArrowArrayInterface(Protocol):
    def __arrow_c_array__(self, requested_schema: PyCapsule = None) -> tuple[PyCapsule, PyCapsule]: ...

def fromarray(obj: SupportsArrayInterface, mode: str | None = None) -> Image: ...
def fromarrow(obj: SupportsArrowArrayInterface, mode: str, size: tuple[int, int]) -> Image: ...
def fromqimage(im: ImageQt.QImage) -> ImageFile.ImageFile: ...
def fromqpixmap(im: ImageQt.QPixmap) -> ImageFile.ImageFile: ...

_fromarray_typemap: Incomplete

def _decompression_bomb_check(size: tuple[int, int]) -> None: ...
def open(
    fp: StrOrBytesPath | IO[bytes], mode: Literal["r"] = "r", formats: list[str] | tuple[str, ...] | None = None
) -> ImageFile.ImageFile: ...
def alpha_composite(im1: Image, im2: Image) -> Image: ...
def blend(im1: Image, im2: Image, alpha: float) -> Image: ...
def composite(image1: Image, image2: Image, mask: Image) -> Image: ...
def eval(image: Image, *args: Callable[[int], float]) -> Image: ...
def merge(mode: str, bands: Sequence[Image]) -> Image: ...
def register_open(
    id: str,
    factory: Callable[[IO[bytes], str | bytes], ImageFile.ImageFile] | type[ImageFile.ImageFile],
    accept: Callable[[bytes], bool | str] | None = None,
) -> None: ...
def register_mime(id: str, mimetype: str) -> None: ...
def register_save(id: str, driver: Callable[[Image, IO[bytes], str | bytes], None]) -> None: ...
def register_save_all(id: str, driver: Callable[[Image, IO[bytes], str | bytes], None]) -> None: ...
def register_extension(id: str, extension: str) -> None: ...
def register_extensions(id: str, extensions: list[str]) -> None: ...
def registered_extensions() -> dict[str, str]: ...
def register_decoder(name: str, decoder: type[ImageFile.PyDecoder]) -> None: ...
def register_encoder(name: str, encoder: type[ImageFile.PyEncoder]) -> None: ...
def _show(image: Image, **options: Any) -> None: ...
def effect_mandelbrot(size: tuple[int, int], extent: tuple[float, float, float, float], quality: int) -> Image: ...
def effect_noise(size: tuple[int, int], sigma: float) -> Image: ...
def linear_gradient(mode: str) -> Image: ...
def radial_gradient(mode: str) -> Image: ...
def _apply_env_variables(env: dict[str, str] | None = None) -> None: ...

_ExifBase: TypeAlias = MutableMapping[int, Any]

class Exif(_ExifBase):
    endian: str | None
    bigtiff: bool
    _loaded: bool
    _data: dict[int, Any]
    _hidden_data: dict[int, Any]
    _ifds: dict[int, dict[int, Any]]
    _info: TiffImagePlugin.ImageFileDirectory_v2 | None
    _loaded_exif: bytes | None
    def __init__(self) -> None: ...
    def _fixup(self, value: Any) -> Any: ...
    def _fixup_dict(self, src_dict: dict[int, Any]) -> dict[int, Any]: ...
    def _get_ifd_dict(self, offset: int, group: int | None = None) -> dict[int, Any] | None: ...
    def _get_head(self) -> bytes: ...
    fp: IO[bytes]
    head: Incomplete
    def load(self, data: bytes) -> None: ...
    def load_from_fp(self, fp: IO[bytes], offset: int | None = None) -> None: ...
    def _get_merged_dict(self) -> dict[int, Any]: ...
    def tobytes(self, offset: int = 8) -> bytes: ...
    def get_ifd(self, tag: int) -> dict[int, Any]: ...
    def hide_offsets(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, tag: int) -> Any: ...
    def __contains__(self, tag: object) -> bool: ...
    def __setitem__(self, tag: int, value: Any) -> None: ...
    def __delitem__(self, tag: int) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
