#!/bin/bash

cd $(git rev-parse --show-toplevel)

./scripts/backquote_as_links.py

glow RELEASE_NOTES.md || exit "Can't find the release notes"

grep version pyproject.toml | v
echo -n "New version: "
read version
echo -n "Release name: "
read title

if [ -z "$title" ]; then
    title="$version"
fi

TOKEN=$(gopass show -o websites/api.github.com/fdev31)
URL=https://api.github.com/repos/hyprland-community/pyprland

echo $version | bumpPyProject.sh

tox || exit -1

pushd ../aurPkgs/pyprland/
echo $version | bumpAurPkg.sh
popd

# Make the release

rel_id=$(http -b -j POST $URL/releases \
        "Accept: application/vnd.github+json" \
        "Authorization: Bearer ${TOKEN}" \
        "X-GitHub-Api-Version: 2022-11-28" \
        tag_name=${version} \
        target_commitish=main \
        "name=${title}" \
        body=@RELEASE_NOTES.md \
    draft:=false prerelease:=false generate_release_notes:=false | jq .id)

echo "RELEASE ID: $rel_id"

echo "Waiting 10s for pypi to update..."
for n in $(seq 10); do
    echo $n
    sleep 1
done

pushd scripts
./update_get-pypr.sh
git commit get-pypr ../pyprland/command.py -m "Update get-pypr script" --no-verify
git push
popd


exit 0
# Upload the standalone version

http -j POST "https://uploads.github.com/repos/hyprland-community/pyprland/releases/${rel_id}/assets?name=pypr" \
    "Accept: application/vnd.github+json" \
    "Authorization: Bearer ${TOKEN}" \
    "X-GitHub-Api-Version: 2022-11-28" \
    "Content-Type: application/octet-stream" < dist/pypr
