#!/bin/sh
cd $(git rev-parse --show-toplevel)
COMMENT='# Automatically updated version'
V=$(git describe --tags)
if ! grep "$V" pyprland/command.py ; then
    sed -Ei "s/^( +)print.*$COMMENT/\1print('$V')  $COMMENT/" pyprland/command.py
fi
