# unused variable (pyprland/common.py:279)
# unused variable (pyprland/common.py:280)
# unused variable (pyprland/common.py:281)
# unused variable (pyprland/common.py:282)
# unused variable (pyprland/common.py:284)
# unused variable (pyprland/common.py:285)
# unused variable (pyprland/common.py:286)
# unused variable (pyprland/common.py:287)
# unused variable (pyprland/common.py:288)
# unused variable (pyprland/common.py:289)
# unused variable (pyprland/common.py:290)
# unused variable (pyprland/common.py:291)
# unused variable (pyprland/common.py:296)
# unused variable (pyprland/common.py:299)
# unused variable (pyprland/common.py:300)
# unused variable (pyprland/common.py:301)
# unused variable (pyprland/common.py:304)
# unused variable (pyprland/common.py:307)
# unused variable (pyprland/common.py:308)
# unused variable (pyprland/common.py:309)
# unused variable (pyprland/common.py:311)
# unused variable (pyprland/common.py:313)
# unused variable (pyprland/common.py:314)
# unused variable (pyprland/common.py:315)
# unused variable (pyprland/common.py:317)
# unused variable (pyprland/common.py:318)
_scratchpads_extension_m  # unused import (pyprland/plugins/scratchpads/objects.py:19)
id  # unused variable (pyprland/types.py:21)
hidden  # unused variable (pyprland/types.py:30)
at  # unused variable (pyprland/types.py:31)
floating  # unused variable (pyprland/types.py:34)
class_  # unused variable (pyprland/types.py:36)
title  # unused variable (pyprland/types.py:37)
initialClass  # unused variable (pyprland/types.py:38)
initialTitle  # unused variable (pyprland/types.py:39)
xwayland  # unused variable (pyprland/types.py:41)
pinned  # unused variable (pyprland/types.py:42)
fullscreen  # unused variable (pyprland/types.py:43)
fullscreenMode  # unused variable (pyprland/types.py:44)
fakeFullscreen  # unused variable (pyprland/types.py:45)
grouped  # unused variable (pyprland/types.py:46)
swallowing  # unused variable (pyprland/types.py:47)
focusHistoryID  # unused variable (pyprland/types.py:48)
id  # unused variable (pyprland/types.py:54)
make  # unused variable (pyprland/types.py:57)
model  # unused variable (pyprland/types.py:58)
serial  # unused variable (pyprland/types.py:59)
refreshRate  # unused variable (pyprland/types.py:62)
activeWorkspace  # unused variable (pyprland/types.py:65)
specialWorkspace  # unused variable (pyprland/types.py:66)
reserved  # unused variable (pyprland/types.py:67)
dpmsStatus  # unused variable (pyprland/types.py:71)
vrr  # unused variable (pyprland/types.py:72)
activelyTearing  # unused variable (pyprland/types.py:73)
currentFormat  # unused variable (pyprland/types.py:75)
availableModes  # unused variable (pyprland/types.py:76)
exc_type  # unused variable (pyprland/aioops.py:31)
exc_val  # unused variable (pyprland/aioops.py:32)
exc_tb  # unused variable (pyprland/aioops.py:33)
init_ipc_folder  # unused function (pyprland/common.py:57)
init_ipc_folder  # unused function (pyprland/common.py:67)
has_state  # unused method (pyprland/plugins/scratchpads/lookup.py:23)
ClientPropGetter  # unused class (pyprland/plugins/scratchpads/objects.py:21)
RetensionTimes  # unused class (pyprland/types.py:11)
SHORT  # unused variable (pyprland/types.py:14)
LONG  # unused variable (pyprland/types.py:15)
major  # unused variable (pyprland/types.py:83)
minor  # unused variable (pyprland/types.py:84)
micro  # unused variable (pyprland/types.py:85)
