name: Nix Setup

on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
      platform:
        default: "ubuntu"
        required: false
        type: string
      do-cache:
        default: false
        required: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  nix:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Run Input: ${{ inputs.command }}"
        run: "${{ inputs.command }}"

      - uses: cachix/cachix-action@v14
        if: ${{ inputs.do-cache }} == true
        with:
          name: hyprland-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
